# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=32, verbose_name='机房名')),
            ],
            options={
                'verbose_name_plural': '机房表',
                'db_table': 'MachineRoom',
            },
        ),
        migrations.CreateModel(
            name='PhysicalDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_name', models.CharField(max_length=32, verbose_name='磁盘名称')),
                ('disk_space', models.IntegerField(default=0, verbose_name='磁盘大小GB')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, max_length=64, verbose_name='服务器名')),
                ('cpu', models.IntegerField(default=0, verbose_name='CPU核数')),
                ('memory', models.IntegerField(default=0, verbose_name='内存大小')),
                ('host_mode', models.CharField(blank=True, max_length=64)),
                ('host_active', models.IntegerField(choices=[(0, '无可用资源'), (1, '有可用资源')], default=1, verbose_name='是否可用')),
                ('idrac_ip', models.CharField(blank=True, max_length=32, verbose_name='IDRAC IP')),
                ('host_ip', models.CharField(blank=True, max_length=32, verbose_name='主机IP')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('room_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MachineRoom')),
            ],
            options={
                'verbose_name_plural': '服务器表',
                'db_table': 'PhysicalMachine',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, '普通用户'), (2, '管理员')], default=1, verbose_name='用户类型')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=64, verbose_name='虚拟机名')),
                ('vm_cpu', models.IntegerField(default=0, verbose_name='虚拟机CPU核数')),
                ('vm_memory', models.IntegerField(default=0, verbose_name='虚拟机内存大小')),
                ('vm_os', models.CharField(default='centos7', max_length=64)),
                ('vm_disk', models.IntegerField(verbose_name='磁盘大小GB')),
                ('vm_ip', models.CharField(max_length=32, verbose_name='虚拟机IP')),
                ('vm_gateway', models.CharField(max_length=32, verbose_name='虚拟机网关')),
                ('vm_audit', models.IntegerField(choices=[(0, '审核不通过'), (1, '审核通过')], default=0, verbose_name='审核状态')),
                ('vm_installed', models.IntegerField(choices=[(0, '未安装'), (1, '已安装')], default=0, verbose_name='是否已安装')),
                ('vm_proposer', models.CharField(max_length=32, verbose_name='申请人')),
                ('vm_createTime', models.DateField(auto_now_add=True)),
                ('vm_updateTime', models.DateField(auto_now=True)),
                ('host_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PhysicalMachine')),
            ],
            options={
                'verbose_name_plural': '虚拟机表',
                'db_table': 'VirtualMachine',
            },
        ),
        migrations.AddField(
            model_name='physicaldisk',
            name='disk_mount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PhysicalMachine'),
        ),
    ]
