# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='vm_datastore',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.PhysicalDisk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='physicaldisk',
            name='disk_space',
            field=models.IntegerField(default=0, verbose_name='磁盘大小TB'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='vm_audit',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核不通过')], default=0, verbose_name='审核状态'),
        ),
    ]
